---
- name: Install Docker and Run Flask-React App
  hosts: ec2
  become: true
  tasks:
    - name: Install required system packages
      dnf:
        name:
          - dnf-plugins-core

        state: present

    - name: Install Docker from Amazon Linux 2023 repository
      dnf:
        name: docker
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to the Docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Pull the Docker images for the app
      shell: |
        docker pull josephinesowmiya/teamroleappfinal-backend:latest
        docker pull josephinesowmiya/teamroleappfinal-frontend:latest

    - name: Run the Flask API container
      shell: |
        docker run -d --name backend -p 5000:5000 josephinesowmiya/teamroleappfinal-backend:latest

    - name: Run the React frontend container
      shell: |
        docker run -d --name frontend -p 3000:3000 josephinesowmiya/teamroleappfinal-frontend:latest
