---
- name: Install Docker and Run Flask-React App
  hosts: ec2
  become: true
  tasks:
    - name: Install required system packages
      dnf:
        name:
          - dnf-plugins-core

        state: present

    - name: Install Docker from Amazon Linux 2023 repository
      dnf:
        name: docker
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to the Docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Ensure project directory exists
      file:
        path: /home/ec2-user/teamroleapp
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Copy docker-compose.yml to the server
      copy:
        src: ./docker-compose.yml  # Ensure this file is in your Ansible playbook directory
        dest: /home/ec2-user/teamroleapp/docker-compose.yml
        owner: ec2-user
        group: ec2-user
        mode: '0644'

    - name: Pull the latest Docker images
      shell: |
        docker-compose -f /home/ec2-user/teamroleapp/docker-compose.yml pull
      args:
        chdir: /home/ec2-user/teamroleapp

    - name: Pull the Docker images for the app
      shell: |
        docker pull josephinesowmiya/teamroleappfinal-backend:latest
        docker pull josephinesowmiya/teamroleappfinal-frontend:latest

    - name: Start the application using Docker Compose
      shell: |
        docker-compose -f /home/ec2-user/teamroleapp/docker-compose.yml up -d
      args:
        chdir: /home/ec2-user/teamroleapp
